name = "QuickBenchmarkTools"
uuid = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
authors = ["Lilith Orion Hafner <lilithhafner@gmail.com> and contributors"]
version = "0.0.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
